### ISSUE TITLE
nng poller test bug

### ISSUE THREAD

**Issue by tomereli** [prplfoundation/prplMesh-framework#10]
There is a bug with nng causing the poller to return POLLIN when there is nothing really to be read.
It was supposed to be solved in nng revision 90467583b7544b68483334070518e29b00ec6d81 but I tried it mayself on latest and all the tests are failing.

Steps to reproduce on Ubuntu 18.04:
- repo init -u https://github.com/prplfoundation/prplMesh-manifest.git
- repo sync
- Build nng as shared lib to multiap/build/install:
```
cd 3rdparty/nng
mkdir build
cmake -B./build -H. -DCMAKE_INSTALL_PREFIX=../../multiap/build/install -DBUILD_SHARED_LIBS=ON
cmake --build build -- install -j
```

- Build framework with MSGLIB=nng and BUILD_TESTS=ON:
```
cd multiap/tools
python3 ./maptools.py build framework -c clean make -f MSGLIB=nng BUILD_TESTS=ON
```

- Verify framework linked with installed nng library by inspecting generated `./framework/common/CMakeFiles/common.dir/link.txt`. If system installed nng was used, add the following line to the Framework's CMakeLists.txt - `list(INSERT CMAKE_FIND_ROOT_PATH 0 ${CMAKE_INSTALL_PREFIX})`

- Run poller test, it will hang `./build/install/bin/tests/common/poller_test`

**Comment by arnout** [comment]
I can't reproduce. Can you double-check that you're running with the right version of libnng, by running poller_test in the same way but with `LD_TRACE_LOADED_OBJECTS=1` in the environment?

**Comment by tomereli** [comment]
You were right, thanks for the tip:
```
tbeliyah@vm815multiap-ubuntu18 ~/work/prpl/dev1/multiap
[]$ LD_TRACE_LOADED_OBJECTS=1 ./build/install/bin/tests/common/poller_test 
	linux-vdso.so.1 (0x00007ffc327aa000)
	mapfcommon.so.1 => /home/tbeliyah/work/prpl/dev1/multiap/build/install/lib/mapfcommon.so.1 (0x00007f306c15b000)
	libelpp.so.1 => /home/tbeliyah/work/prpl/dev1/multiap/build/install/lib/libelpp.so.1 (0x00007f306bf1d000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f306bb94000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f306b97c000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f306b58b000)
	libnng.so.1 => /usr/local/lib/libnng.so.1 (0x00007f306b323000)
	libjson-c.so.3 => /lib/x86_64-linux-gnu/libjson-c.so.3 (0x00007f306b118000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f306aef9000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f306ab5b000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f306c37c000)
```
So apparently https://github.com/prplfoundation/prplMesh-framework/pull/11 doesn't work.

**Comment by tomereli** [comment]
Fixed https://github.com/prplfoundation/prplMesh-framework/pull/11 and verified that with the manifest nng version the issue doesn't reproduce, so closing the issue.
